### ISSUE TITLE
Are the engines restrictions necessary?

### ISSUE THREAD

**Issue by jucallej** [LottieFiles/jlottie#20]
Hi 👋,

Setting the yarn version and node version here https://github.com/LottieFiles/jlottie/blob/main/package.json#L11 forces people to use yarn 2 and at least node 14 (otherwise it fails doing an npm install which is suggested https://github.com/LottieFiles/jlottie/tree/37f161e2a9ebf12994166e13c60a5bb940783d01#in-javascript-or-typescript). Is there any reason for that? Ideally I would drop/remove both from the package.json as not every project might be using node 14 and a lot of people can be using npm instead of yarn.

What do you guys think? 😀

Thanks!

**Comment by shaafiee** [comment]
Hi,

We believe that Yarn 2 is sufficiently matured enough for everyone to have adopted it as the default version. So, we will be leaving that requirement unchanged.

We shall also leave the node version requirement unchanged since the current recommended LTS version of Node is 14.17.3. The other reason being that jlottie is still under development.

As for the issues encountered whilst installing jlottie via npm, we have identified a problem in our package.json and will be rectifying this in the next build, which should be arriving by Friday.

**Comment by shaafiee** [comment]
Since my last reply to this thread, we have made a change to our stand since then. We have decided to remove engine requirements from package.json altogether.

We acknowledge that your suggestion was a sound one, @jucallej.

**Comment by jucallej** [comment]
Thanks @shaafiee  🙏, I'm closing this issue as you've already remove it https://github.com/LottieFiles/jlottie/commit/7d7b265e9154d53014075dda7757d806bbef08d5 🙌
